### ISSUE TITLE
Can we disable the `Learn More` square on index somehow?

### ISSUE THREAD

**Issue by bastianb** [kevana/ui-for-docker#166]
It's been very annoying when refreshing page.

**Comment by kevana** [comment]
:+1: This is leftover from a long time ago (didn't Docker switch from `.io` to `.com` 2 years ago?). What would you like to see on the dashboard? In my installation we use a [custom dashboard](https://medium.com/@kevanahlquist/dockerui-at-bluestem-2890bf1bcd45) but I haven't heard much about what other users want to see.

**Comment by taiidani** [comment]
Popping over here from #150 to provide feedback --

I don't mind the jumbotron on the first page load. Refreshes though can make it get on one's nerves. I'm :+1: with it going away! If not, perhaps set a local storage bit or cookie in the user's browser so it doesn't recur?

Things I'd love on the dashboard:
* Currently running containers and their statuses (already present). Simple actions on these such as View Logs, Stats, etc. would be great. Related:
 * A running stream of recent logs for all containers (Eg: `docker-compose logs`)
 * System-wide memory/CPU summary for all running containers, aggregated and/or separated by container.
* Indications of which containers are running on which networks, assuming Docker 1.9+ is present.

More important than all of these though is a rapid page load. Right now the Dashboard loads wicked fast and I'd love for it to stay that way :)

**Comment by kevana** [comment]
Put the jumbotron state in localStorage so we should only see it once per browser now, in latest `0.9.0-beta` image on the hub.

**Comment by deviantony** [comment]
@kevana can we close this one?

**Comment by kevana** [comment]
Yep, original problem was solved. May want to open up a new feature issue for a newer shinier dashboard
