### ISSUE TITLE
Error: image dockerui/dockerui not found.

### ISSUE THREAD

**Issue by dimorinny** [kevana/ui-for-docker#200]
```
docker run -d -p 9000:9000 --privileged -v /var/run/docker.sock:/var/run/docker.sock dockerui/dockerui                            
Unable to find image 'dockerui/dockerui:latest' locally
Pulling repository docker.io/dockerui/dockerui
docker: Error: image dockerui/dockerui not found.
See 'docker run --help'.
```

**Comment by quater** [comment]
I am having the same problem, as of my logs this problem started about 12 hours ago (21:00 BST). It appears that the "dockerui/dockerui" images is not located on Docker Hub any more. :(

**Comment by styfle** [comment]
Probably related to #197

**Comment by kevana** [comment]
Sorry for the inconvenience everyone, while we get things sorted out you'll need to clone the repo and manually build the image instead of pulling from the hub.

```
git clone https://github.com/crosbymichael/not-dockers-ui.git
cd not-dockers-ui
npm install
grunt run     # Takes a while, will build the image locally as dockerui:latest and run it
```

**Comment by pascalandy** [comment]
cool thanks !

**Comment by nitin-amp** [comment]
Just a couple of gotchas while building:
- grunt/ grunt-cli should be installed in your dev environment (`npm install -g grunt`, ...)
- docker daemon should be running. `grunt run` fails if it is unable to access the one of the images

HTH

**Comment by kevana** [comment]
As soon as a name is decided re: #197 (hopefully tomorrow) I'll publish a new automated image on the hub. Sorry for breaking things, I know this is really inconvenient but we ended up on the wrong side of the Docker branding guidelines. The vulnerability disclosures made us realize there was confusion about this being an official Docker project (it's not).

**Comment by kevana** [comment]
No word back on renaming/not renaming yet, for now the latest version (`0.10.1`) is published at [kevan/dockerui](https://hub.docker.com/r/kevan/dockerui/) on the hub. I'll follow up when I hear back.

**Comment by kevana** [comment]
Hey, the project now lives [on the hub](https://hub.docker.com/r/uifd/ui-for-docker/) at: `uifd/ui-for-docker`

**Comment by linquize** [comment]
HA!  You rename the project again.
