### ISSUE TITLE
DockerUI behind jwilder/nginx-proxy

### ISSUE THREAD

**Issue by julianxhokaxhiu** [kevana/ui-for-docker#204]
Hi,

I'm trying to run DockerUI through this way ( Docker Engine **1.10.3** ):

```bash
sudo docker run \
    --restart=always \
    --name="dockers.julian.lan" \
    --privileged \
    -d \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e "VIRTUAL_HOST=dockers.julian.lan" \
    -e "VIRTUAL_PORT=9000" \
    uifd/ui-for-docker &>/dev/null
```

but when I go then to `http://dockers.julian.lan` I don't see any container, just a spinner loading forever. If I inspect the console, I see that there's a 500 internal server error on the URL when you pull the JSON data.

What am I doing wrong? My goal is to connect only through Socket, so if possible, to avoid TCP binding.

Thanks in advance.

**Comment by kevana** [comment]
Sorry, this took me a while to see. This happens if the proxy isn't using HTTP 1.1, related to #29. You can modify the default Nginx settings on the proxy, look under the heading "Replacing default proxy settings" [here](https://hub.docker.com/r/jwilder/nginx-proxy/) for details.

**Comment by julianxhokaxhiu** [comment]
Sorry but the proxy is coming by default with HTTP 1.1 support, so I don't see where is the fault then :\

```nginx
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}

# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}

# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
```

Any other clue?

**Comment by kevana** [comment]
Is the connection header being emptied or set to `close`? I had to empty it to get it to work.

**Comment by julianxhokaxhiu** [comment]
Is there a way where I can see this? On your docker or ony reverse proxy logs?

**Comment by kevana** [comment]
Not without modifying the code or opening up a network capture program

**Comment by julianxhokaxhiu** [comment]
Can you maybe provide a "debug" version of your Docker?

**Comment by kerongon** [comment]
I've been running docker ui like this for months now. You need to create a vhost. d folder and make a text file with your domain name in it, restart your proxy container and it should work.
Here's the code I use.

  #http 1.1 support...

proxy_http_version 1.1;
proxy_set_header Connection "";
auth_basic "Restricted Content";
auth_basic_user_file /etc/nginx/.htpasswd;  // password protection
                 
proxy_redirect     off;
proxy_set_header   Host $host;
proxy_set_header   X-Real-IP $remote_addr;
proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header   X-Forwarded-Host $server_name;

**Comment by julianxhokaxhiu** [comment]
@kerongon thanks for the help but we cleared already that part. The proxy configuration is not the issue here.

**Comment by klaszlo** [comment]
I think I have the same issue. 
ui for docker do not load behind nginx-reverse proxy docker container. 
doing sudo docker logs [IMAGEID], I see this:

    open authKey.dat: no such file or directory
    2016/05/02 16:11:26 persistent connection closed
    2016/05/02 16:11:26 persistent connection closed
    2016/05/02 16:11:26 persistent connection closed

Opening directly the port (myserver.ip:9000) works as expected.

I launched it via:

    sudo docker run --restart=always \
    -d -p 9000:9000 -e VIRTUAL_HOST=$VIRTUALHOST \
    --privileged -v /var/run/docker.sock:/var/run/docker.sock uifd/ui-for-docker

**Comment by julianxhokaxhiu** [comment]
@klaszlo exactly that issue

**Comment by kevana** [comment]
I believe this is the same connection header issue. Please make sure it is
emptied

**Comment by klaszlo** [comment]
@kevana do you have any idea why the original dockerui
(inspecting the image it was created on 2015-12-15 T 05:15:53.7 ) has not this issue?

**Comment by kevana** [comment]
What version of DockerUI is your old one? 0.10.1 added CSRF protection on the server. When it fails it usually has pretty clear error messages that tokens are missing or mismatched.

**Comment by julianxhokaxhiu** [comment]
@kevana let's say is the Connection header that should be empty.

Now my question is: IF this is true, why the homepage of your docker shows through reverse proxy, while the JSON url doesn't, and indeed throws a 500 error? To me this looks more like an internal failure of the dockers, not of the reverse proxy. And the connection closed seems that something is triggering it, but I found really no clues regarding the connection header. And finally on jwilder/nginx-proxy this header IS cleared, since it's pretty much working with any other container.

What I cannot understand is why is it so difficult to provide more logs on the docker so we can maybe find where's the culprit. Maybe place a dump of the stack trace so we can understand what is going on... ( like a big try...catch )

**Comment by kevana** [comment]
The homepage loads because static assets for this project are served from a [FileServer](https://github.com/kevana/ui-for-docker/blob/master/dockerui.go#L78) while the API calls are routed through a [ReverseProxy](https://github.com/kevana/ui-for-docker/blob/master/dockerui.go#L31). Something about the connection header triggers an error with unix sockets, I don't know why (bug is probably [here](https://github.com/kevana/ui-for-docker/blob/master/dockerui.go#L31-L53)).

I'm still able to run the [nginx example](https://github.com/kevana/ui-for-docker/tree/master/examples/nginx-basic-auth) in the repo with no issues, that's why I believe @kerongon is correct. `proxy_set_header Connection "";` needs to be set manually. 
By default the jwilder proxy is setting the Connection header to `close`:

1. [L31](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L31): If the `Upgrade` header is empty the output of the `$proxy_connection` map is set to `close`

2. [L50](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L50): Sets the header to the output of the `$proxy_connection` map

If anyone that knows their way around unix sockets in Golang can track down the bug I'll be happy to fix it, but in the meantime there's a workaround that you can use right now.

**Comment by klaszlo** [comment]
@kevana 
> What version of DockerUI is your old one?

I believe it is right after this commit: https://github.com/kevana/ui-for-docker/commit/2f003a5bb59f8dc068426f48073abb0428ff36ba

The "<none>:<none>" string is pretty unique, and the generated .js source contains it.
Also dockerui.js contains this version string:
/*! dockerui - v0.8.1 - 2015-12-14

While the new one (uifd):
/*! dockerui - v0.10.1-beta - 2016-04-02

The bundled angular.js file is also different (1.3.15 vs. 1.5.3).

**Comment by kevana** [comment]
@klaszlo Were you running the `dockerui/dockerui` image behind an nginx proxy as well or hitting it directly?

**Comment by julianxhokaxhiu** [comment]
Ok well, regarding the singular bug I'll work myself tomorrow to see what I can catch @kevana 
---
Meanwhile, for anyone who's suffering this, there's a super-easy-fix! You can to use the [Per-Virtual_Host location configuration](https://github.com/jwilder/nginx-proxy#per-virtual_host-location-configuration). In your `vhost.d` mapped volume directory, place this line

```
proxy_set_header Connection '';
```

and save it with the name `<your_VIRTUAL_HOST_name_here>_location` like, in my case would be `dockers.julian.lan_location`. Once this is done, just `stop/start` your `jwilder/nginx-proxy` docker and voilà! UI For Docker will be up and running :)

**Comment by deviantony** [comment]
Seems that a solution was found here, still need to keep this issue open?

**Comment by julianxhokaxhiu** [comment]
Approved :) you can close this

**Comment by deviantony** [comment]
Nice :+1:
