### ISSUE TITLE
Latest dockerui image seems broken...

### ISSUE THREAD

**Issue by ArcticSnowman** [kevana/ui-for-docker#206]
Latest dockerui image seems broken...

The 'docker log' output is only `open authKey.dat: no such file or directory`

**Comment by kevana** [comment]
That message shows on first boot, it just [generates a new CSRF key and continues booting](https://github.com/kevana/ui-for-docker/blob/master/dockerui.go#L97). Are you able to access the UI?

**Comment by ArcticSnowman** [comment]
OK my bad.... it was a nginx issue in front of the ui-for-docker image...
