### ISSUE TITLE
How to start project with dockerui.go

### ISSUE THREAD

**Issue by sureshchouksey** [kevana/ui-for-docker#209]
Hi,
     I want to run project with angularjs. Now i am trying to run dockerui.go for creating server and run the project.Kindly help me how to compile and run "dockerui.go" and how to integrate with grunt and "app/app.js". This is very important for me.

**Comment by kevana** [comment]
The [wiki](https://github.com/kevana/ui-for-docker/wiki/Running-UI-for-Docker) has directions for compiling and running the project, let me know if you have questions after reading through there.

**Comment by deviantony** [comment]
A link to the Wiki is already displayed in the README, no need for evolution on this issue.
