### ISSUE TITLE
Run Docker with source code in a mounted volume - source files changes not reflecting

### ISSUE THREAD

**Issue by riteshkapadia** [kevana/ui-for-docker#214]
Hi,

The project you have build is amazing. I am running into issues while i want to change the HTML, Angular part for some pages locally on my machine.

I refereed the "Run Docker with source code in a mounted volume". Changed my docker file, and started the docker. It refers to the default created docker(uifd/ui-for-docker) and project runs fine at 9000 port.

I then started the grunt watch, it reflects the changes that i am doing to the files under app. But same changes are reflected on the running browser. Is there something i am missing?

Note:I am using Ubuntu 15.04.  I read the comment for OS X that source files might not reflect.

I need to just understand how can i check my changes that i have done to html angular part locally?

Thanks,
Ritesh Kapadia

**Comment by riteshkapadia** [comment]
If i do grunt run-dev, i am getting stuck at following :

Running "shell:buildImage" (shell) task
time="2016-06-03T20:39:05+05:30" level=error msg="Can't exclude whole path, excluding pattern: *" 
Sending build context to Docker daemon 3.072 kB
Sending build context to Docker daemon 
Step 0 : FROM scratch
 ---> 
Step 1 : COPY dist /
time="2016-06-03T20:39:05+05:30" level=info msg="dist: no such file or directory" 
Warning: Command failed: docker build --rm -t ui-for-docker .
time="2016-06-03T20:39:05+05:30" level=error msg="Can't exclude whole path, excluding pattern: *" 
time="2016-06-03T20:39:05+05:30" level=info msg="dist: no such file or directory" 
 Use --force to continue.

The dist folder is present with the required build binary.

Please help.

Thanks,
Ritesh Kapadia.

**Comment by kevana** [comment]
Are you running Docker 1.6? If so you can comment out that exclude line in .dockerignore.

**Comment by riteshkapadia** [comment]
Following is my .dockerignore now:

!dist

This ran the project, but i can see the folder structure on browser when i hit:
http://0.0.0.0:9000/#/

I cannot see the docker ui :(

Thanks,
Ritesh Kapadia

**Comment by riteshkapadia** [comment]
Also, i goal i had mentioned in the first comment, please let me know if there is any easier way to achieve this.

Thanks,
Ritesh Kapadia

**Comment by kevana** [comment]
Could you post a screenshot? There's nothing in the app that would show you a directory listing (folder structure) when it's running.

**Comment by kevana** [comment]
I use `grunt run-dev` because I'm on OS X and working with the source code mounted has never worked due to the sendfile issues, that's the easiest way for me.

**Comment by riteshkapadia** [comment]
![screenshot from 2016-06-03 21 09 02](https://cloud.githubusercontent.com/assets/5976629/15784282/78fc9f28-29cf-11e6-82f5-bfe76e903f90.png)

**Comment by riteshkapadia** [comment]
Earlier normally when i deployed the docker it was working fine.
But after this .dockerignore change i was able to run the commany dev-run but this directory structure came up

**Comment by kevana** [comment]
That's a new one. Try deleting the `.dockerignore` file entirely and rebuilding.

**Comment by riteshkapadia** [comment]
tired, the page is not loading anything now :(

**Comment by riteshkapadia** [comment]
I am able to run ui-for docker, using following docker file

FROM scratch
COPY dist /app
EXPOSE 9000
WORKDIR /app
ENTRYPOINT ["ui-for-docker"]

I did everything as mentioned in wiki Run Docker with source code in a mounted volume but after i start the grunt watch and start making changes to dashboard.html the changes **are not reflected** on the browser. On terminal it shows that changes made to the file.

The ui-for-docker is running perfectly fine now.

Thanks,
Ritesh Kapadia.

**Comment by riteshkapadia** [comment]
Ok, so angular.js is getting generated blank in dist folder.

Any pointers?

**Comment by deviantony** [comment]
@riteshkapadia did you manage to solve your issue?

**Comment by riteshkapadia** [comment]
yes this is resolved, problem was with bower install.

**Comment by deviantony** [comment]
Perfect :+1:
