### ISSUE TITLE
Date format forced to US format (mm/dd/yyyy)

### ISSUE THREAD

**Issue by bradwood** [kevana/ui-for-docker#216]
Is is possible to change this to dd/mm/yyyy or even yyyy-mm-dd? The US format is both annoying and can be misinterpreted outside the US.

**Comment by linquize** [comment]
I do not like the date format either.

**Comment by vyscond** [comment]
👍 on use ISO formats

**Comment by deviantony** [comment]
ISO 8601 compliant dates would be better indeed.

**Comment by deviantony** [comment]
:+1:
