### ISSUE TITLE
"shell:buildBinary" (shell) task fails

### ISSUE THREAD

**Issue by Dylanvdb** [kevana/ui-for-docker#219]
Hi,

I'm trying to customize ui-for-docker, so I followed the "Developing UI for Docker" steps in the wiki. But when I try to run "grunt" from the terminal, it says the following: 

> Warning: Command failed: docker run --rm -v /Users/dylanvandenbrink/dev/dockerui/ui-for-docker/src centurylink/golang-builder && shasum ui-for-docker > ui-for-docker-checksum.txt && mkdir -p dist && mv ui-for-docker dist/
 Use --force to continue.

Environment details:
Docker: 
- Docker version 1.8.2, build 0a8c2e3 running on Ubuntu 14.04.4 LTS

Client:
- Node v5.9.0
- OS X El Capitan 10.11.5

**Comment by deviantony** [comment]
The `grunt build` (which is only the build of the Go binary) works well on my laptop after a clean checkout.

Could you try the following `docker run --rm -v $(pwd):/src centurylink/golang-builder` and give us the output?

I'm not sure but it seems that it lacks a separator between the path to the volume on your host and the path in the container (e.g. /Users/dylanvandenbrink/dev/dockerui/ui-for-docker **:** /src and not /Users/dylanvandenbrink/dev/dockerui/ui-for-docker /src)

**Comment by Dylanvdb** [comment]
Thanks for looking into my issue, I've tried the command and it gives me the same error.

`Error: Must mount Go source code into /src directory`

**Comment by Dylanvdb** [comment]
Btw the docker instance is not running on my local machine (e.g. localhost). It's running on a external machine. This could be the problem right?

**Comment by deviantony** [comment]
@Dylanvdb yeap, definitely. You cannot map volumes from your host on an external machine.

The `grunt` commands are meant to be executed locally.
