### ISSUE TITLE
Unable to start a stopped container

### ISSUE THREAD

**Issue by wumpz** [kevana/ui-for-docker#234]
My guess it was happening after upgrading to docker 1.12. After that I was not able to start a previously stopped container. Restarting it using dockers cli works just fine. Using the restart button for a running container does work as well.
So is there an error log somewhere within dockerui.

**Comment by deviantony** [comment]
Yes, I think that a few things are broken with Docker 1.12, we need to review the UI to support it.

**Comment by i814u2** [comment]
I'm seeing similar behavior. I tried on 0.10.1 and also 0.11.0-beta. 
Running docker 1.12, Ubuntu 16.04.1.
journalctl -xe shows the following (container id edited for length):

> level=error msg="Handler for POST /containers/<containerID>/start returned error: starting container with HostConfig was deprecated since v1.10 and removed in v1.12
