### ISSUE TITLE
Build on docker hub

### ISSUE THREAD

**Issue by matteoturra** [kevana/ui-for-docker#239]
I think the docker hub latest image https://hub.docker.com/r/uifd/ui-for-docker/tags/ is not alligned with the documentation page https://github.com/kevana/ui-for-docker

**Comment by kevana** [comment]
Could you elaborate on this, are tags missing?

**Comment by matteoturra** [comment]
I tried the command
`docker run -d -p 9000:9000 --privileged uifd/ui-for-docker -H tcp://127.0.0.1:2375`
and I got this on the log:
```
Usage of /dockerui:
  -a string
     Path to the assets (default ".")
  -e string
     Dockerd endpoint (default "/var/run/docker.sock")
  -p string
     Address and port to serve dockerui (default ":9000")
```
I think the latest version published on the hub is not updated. Isn't it?

**Comment by deviantony** [comment]
From what I can see in this comment https://github.com/kevana/ui-for-docker/pull/230#issuecomment-232257580 I'd say it's built on the hub as `0.11.0-beta` give that a try:

```shell
docker run -d -p 9000:9000 --privileged uifd/ui-for-docker:0.11.0-beta -H tcp://127.0.0.1:2375
```

But indeed, latest is not pointing to the latest changes (e.g. the master branch, so the documentation in the Readme is related to the `0.11.0-beta` tag).

**Comment by matteoturra** [comment]
Thanks, It works.
