### ISSUE TITLE
Nginx binding to `/docker`

### ISSUE THREAD

**Issue by TheKnarf** [kevana/ui-for-docker#246]
I set my nginx site config to the following:

```
location /docker {
   proxy_pass http://ui_for_docker/;
   ...
}
```

as my main url `/` is already in use for something else, and why would I want my main webpage to just show `ui-for-docker`?

The nginx config works, as in I get to download the html page. But then the `ui-for-docker` application redirects me to `http://mydomain/#/` instead of `http://mydomain/docker/#/`.

**Comment by deviantony** [comment]
Have you tried the solution in #97 posted here: https://github.com/kevana/ui-for-docker/issues/97#issuecomment-239664318 ?

**Comment by TheKnarf** [comment]
**That worked**
(*I just had some problems with my browser cache, so testing it initially didn't seem to work*).

Perhaps that you could update the [UI for Docker with Nginx HTTP Auth](https://github.com/kevana/ui-for-docker/wiki/UI-for-Docker-with-Nginx-HTTP-Auth) to include the rewrite part? As I imagine that most people use this as a reference when they set up nginx.

**Comment by deviantony** [comment]
Cool :)

I've updated the conf in the Wiki.

**Comment by TheKnarf** [comment]
You might want to note in the wiki that if you're using `nginx` as a reverse proxy, then you do not need to bind the docker container to a public port. So

```
docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock uifd/ui-for-docker
```

works fine.
