### ISSUE TITLE
Unable to start a stopped container v2

### ISSUE THREAD

**Issue by developster** [kevana/ui-for-docker#249]
Start button from container details view still does not work (url http://localhost:9000/#/containers/<hash>/).

As a workaround, in container list view, I can check this job and from actions select start.

**Comment by developster** [comment]
This issue is related to https://github.com/kevana/ui-for-docker/issues/234.

**Comment by deviantony** [comment]
This has been fixed by #242 but I think it has not been built and thus is not available on the Dockerhub yet.

ping @kevana

**Comment by developster** [comment]
I checked and #242 was merged on 7 Sept, then on same day v0.11.0 was released. I am running v0.11.0.

**Comment by deviantony** [comment]
Nah sorry, fixed by #245 which is not part of the release on Dockerhub.

**Comment by deviantony** [comment]
@developster as UIFD is now deprecated in favor of **portainer**, there won't be anymore releases. Please have a look at it here: https://github.com/portainer/portainer

**Comment by developster** [comment]
Thanks for the update.
