### ISSUE TITLE
CSRF auth key problem

### ISSUE THREAD

**Issue by adi90x** [kevana/ui-for-docker#255]
Hello, just trying to start UIFD and containers seems to be block on `Unable to find an existing CSRF auth key. Generating a new key`

I can connect to the web interface however nothing dynamic is displayed .
And whenever I connect to web interface , UIFD log : `persistent connection closed`

Is it a known issue ?

**Comment by deviantony** [comment]
Hi @adi90x, 

the first log `Unable to find an existing CSRF auth key. Generating a new key` is an information message. However the second one `persistent connection closed` indicates an error.

Could you give us information about your docker version? E.g. `docker info` and `docker version`

**Comment by adi90x** [comment]
Hello deviantony, 
I will close the issue as I was unable to reproduce it with a clean docker setup.
