### ISSUE TITLE
How to add RO volume

### ISSUE THREAD

**Issue by bithost** [kevana/ui-for-docker#259]
Hello, 
  I just started using UI for docker but i can't find how to add bindings to volumes on local storage when i am creating container. After container was created i set up Bindings and they work. Can someone tell me how i can set up bindings when i am creating container?

Thanks, 
  Tadas

**Comment by deviantony** [comment]
@bithost have a look at **portainer**: https://github.com/portainer/portainer

It can be used as a replacement for UIFD and it allows to declare read-only volumes when creating containers.

**Comment by bithost** [comment]
@deviantony, installed portainer and it looks very nice. Thanks!
